import json
import os

def create_notebook():
    nb = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Guided Inference: Qualitative Hints for Quantitative Predictions\n",
                    "\n",
                    "This notebook evaluates Gemini 3.1 Flash lite's predictive performance when provided with qualitative \"hints\" about the semantic content of video titles. These hints are derived from the 15-dimensional PCA space and OLS model significance found in the `numeric-inference` notebook.\n",
                    "\n",
                    "## Methodology:\n",
                    "1. **Contextual Prompting**: For each channel, the LLM is provided with global success drivers, definitions of significant semantic dimensions, and statistical benchmarks.\n",
                    "2. **Qualitative Hints**: For each video in a test batch (10 videos), the LLM receives labels indicating how the title scores on the 5 most significant dimensions for that channel. Labels are assigned based on the training distribution (e.g., \"significantly negative\" for top 5% values).\n",
                    "3. **Zero-Shot Prediction**: The LLM predicts logarithmic views for each title.\n",
                    "4. **Comparative Evaluation**: Accuracy is measured against actual views and OLS numeric benchmarks using MAE and R2 metrics.\n",
                    "\n",
                    "## 1. Setup and Dependencies"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "!pip install -q -U google-generativeai pandas numpy matplotlib seaborn statsmodels scikit-learn\n",
                    "\n",
                    "import os\n",
                    "import json\n",
                    "import time\n",
                    "import numpy as np\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    "import seaborn as sns\n",
                    "from google.colab import drive, userdata\n",
                    "import google.generativeai as genai\n",
                    "from datetime import datetime\n",
                    "from sklearn.metrics import mean_absolute_error, r2_score\n",
                    "from scipy import stats\n",
                    "\n",
                    "# Mount Google Drive\n",
                    "drive.mount('/content/drive')\n",
                    "\n",
                    "# Configure Gemini\n",
                    "GEMINI_API_KEY = userdata.get('GOOGLE_API_KEY')\n",
                    "genai.configure(api_key=GEMINI_API_KEY)\n",
                    "MODEL_NAME = 'gemini-3.1-flash-lite-latest'\n",
                    "\n",
                    "# Constants\n",
                    "BASE_PATH = '/content/drive/MyDrive/numeric_inference_outputs/'\n",
                    "EVAL_DATA_FILE = os.path.join(BASE_PATH, 'top_significant_channels_eval.json')\n",
                    "LLM_ANALYSIS_FILE = os.path.join(BASE_PATH, 'llm_analysis_results.json')\n",
                    "OUTPUT_FILE = os.path.join(BASE_PATH, 'guided_inference_results.json')\n",
                    "CACHE_FILE = os.path.join(BASE_PATH, 'guided_inference_cache.json')"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 2. Load Data and Define Label Distribution\n",
                    "\n",
                    "We map embedding values to qualitative labels based on the following training distribution:\n",
                    "- significantly negative: bottom 5%\n",
                    "- negative: next 10%\n",
                    "- mildly negative: next 20%\n",
                    "- neutral: middle 30%\n",
                    "- mildly positive: next 20%\n",
                    "- positive: next 10%\n",
                    "- significative positive: top 5%"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "with open(EVAL_DATA_FILE, 'r') as f:\n",
                    "    eval_dataset = json.load(f)\n",
                    "\n",
                    "with open(LLM_ANALYSIS_FILE, 'r') as f:\n",
                    "    llm_analysis = json.load(f)\n",
                    "\n",
                    "LABEL_ORDER = [\n",
                    "    \"significantly negative\", \"negative\", \"mildly negative\", \n",
                    "    \"neutral\", \n",
                    "    \"mildly positive\", \"positive\", \"significative positive\"\n",
                    "]\n",
                    "\n",
                    "DISTRIBUTION = [0.05, 0.10, 0.20, 0.30, 0.20, 0.10, 0.05]\n",
                    "CUMULATIVE_DIST = np.cumsum(DISTRIBUTION)\n",
                    "\n",
                    "def get_channel_stats(train_videos):\n",
                    "    log_views = np.log1p([v['actual_views'] for v in train_videos])\n",
                    "    return {\n",
                    "        'min': float(np.min(log_views)),\n",
                    "        'max': float(np.max(log_views)),\n",
                    "        'mean': float(np.mean(log_views)),\n",
                    "        'q1': float(np.percentile(log_views, 25)),\n",
                    "        'median': float(np.median(log_views)),\n",
                    "        'q3': float(np.percentile(log_views, 75))\n",
                    "    }\n",
                    "\n",
                    "def get_dimension_thresholds(channel_data):\n",
                    "    train_vids = channel_data['train_videos']\n",
                    "    p_values = np.array(channel_data['model']['p_values'][1:])\n",
                    "    sig_indices = np.argsort(p_values)[:5]\n",
                    "    \n",
                    "    thresholds = {}\n",
                    "    for idx in sig_indices:\n",
                    "        # Use raw embedding values for thresholds\n",
                    "        vals = [v['reduced_embedding'][idx] for v in train_vids]\n",
                    "        t_vals = [np.percentile(vals, p * 100) for p in CUMULATIVE_DIST[:-1]]\n",
                    "        thresholds[int(idx)] = t_vals\n",
                    "        \n",
                    "    return thresholds, sig_indices\n",
                    "\n",
                    "def get_label(val, thresholds):\n",
                    "    for idx, t in enumerate(thresholds):\n",
                    "        if val <= t:\n",
                    "            return LABEL_ORDER[idx]\n",
                    "    return LABEL_ORDER[-1]\n",
                    "\n",
                    "channel_info = {}\n",
                    "for c in eval_dataset:\n",
                    "    cid = c['channel_id']\n",
                    "    stats_dict = get_channel_stats(c['train_videos'])\n",
                    "    thresh, sig_idx = get_dimension_thresholds(c)\n",
                    "    channel_info[cid] = {\n",
                    "        'stats': stats_dict,\n",
                    "        'thresholds': thresh,\n",
                    "        'sig_indices': sig_idx\n",
                    "    }\n",
                    "\n",
                    "print(f\"Processed {len(eval_dataset)} channels.\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 3. Utility Functions"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def load_cache():\n",
                    "    if os.path.exists(CACHE_FILE):\n",
                    "        with open(CACHE_FILE, 'r') as f:\n",
                    "            return json.load(f)\n",
                    "    return {}\n",
                    "\n",
                    "def save_cache(cache):\n",
                    "    with open(CACHE_FILE, 'w') as f:\n",
                    "        json.dump(cache, f, indent=4)\n",
                    "\n",
                    "def get_gemini_completion(prompt, cache, key, retries=3, sleep_time=2):\n",
                    "    if key in cache:\n",
                    "        return cache[key]\n",
                    "\n",
                    "    model = genai.GenerativeModel(MODEL_NAME)\n",
                    "\n",
                    "    for i in range(retries):\n",
                    "        try:\n",
                    "            response = model.generate_content(prompt)\n",
                    "            text = response.text\n",
                    "            cache[key] = text\n",
                    "            save_cache(cache)\n",
                    "            time.sleep(sleep_time)\n",
                    "            return text\n",
                    "        except Exception as e:\n",
                    "            print(f\"Error on attempt {i+1}: {e}\")\n",
                    "            if i < retries - 1:\n",
                    "                time.sleep(sleep_time * (i + 1))\n",
                    "            else:\n",
                    "                raise e\n",
                    "    return None\n",
                    "\n",
                    "def parse_json_response(text):\n",
                    "    import re\n",
                    "    try:\n",
                    "        # Strip markdown\n",
                    "        text = re.sub(r'```json\\s*', '', text)\n",
                    "        text = re.sub(r'```\\s*', '', text)\n",
                    "        # Find JSON object or list\n",
                    "        match = re.search(r'(\\{.*\\}|\\[.*\\])', text, re.DOTALL)\n",
                    "        if match:\n",
                    "            return json.loads(match.group())\n",
                    "    except:\n",
                    "        pass\n",
                    "    return None"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 4. Guided Inference Engine\n",
                    "\n",
                    "We predict views in batches of 10. For each title, we provide qualitative hints (labels) for the 5 most significant dimensions."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "cache = load_cache()\n",
                    "all_results = []\n",
                    "\n",
                    "for channel in eval_dataset:\n",
                    "    cid = channel['channel_id']\n",
                    "    cname = channel['channel_name']\n",
                    "    info = channel_info[cid]\n",
                    "    stats_vals = info['stats']\n",
                    "    sig_indices = info['sig_indices']\n",
                    "    thresholds = info['thresholds']\n",
                    "    \n",
                    "    global_desc = llm_analysis['global_performance_descriptions'].get(cid, \"\")\n",
                    "    dim_analysis = llm_analysis['channel_significant_dimension_analysis'].get(cid, \"\")\n",
                    "    dim_definitions = [llm_analysis['dimension_definitions'][idx] for idx in sig_indices]\n",
                    "    \n",
                    "    test_vids = channel['test_videos']\n",
                    "    channel_results = []\n",
                    "    \n",
                    "    print(f\"\\n>>> Processing Channel: {cname}\")\n",
                    "    \n",
                    "    for i in range(0, len(test_vids), 10):\n",
                    "        batch = test_vids[i:i+10]\n",
                    "        batch_titles_lower = [v['title'].lower() for v in batch]\n",
                    "        \n",
                    "        video_list_str = \"\"\n",
                    "        for v in batch:\n",
                    "            hints = []\n",
                    "            for idx in sig_indices:\n",
                    "                label = get_label(v['reduced_embedding'][idx], thresholds[idx])\n",
                    "                hints.append(f\"Dim {idx}: {label}\")\n",
                    "            video_list_str += f\"- Title: {v['title']}\\n  Hints: {', '.join(hints)}\\n\"\n",
                    "        \n",
                    "        dim_info_str = \"\\n\".join([f\"Dimension {idx}: {desc}\" for idx, desc in zip(sig_indices, dim_definitions)])\n",
                    "        \n",
                    "        prompt = f\"\"\"You are a YouTube performance analyst.\n",
                    "\n",
                    "Channel: {cname}\n",
                    "\n",
                    "Global Success Drivers:\n",
                    "{global_desc}\n",
                    "\n",
                    "Significant Dimension Definitions:\n",
                    "{dim_info_str}\n",
                    "\n",
                    "Significant Dimension Analysis for this channel:\n",
                    "{dim_analysis}\n",
                    "\n",
                    "Training Data Metrics (Logarithmic Views):\n",
                    "- Max: {stats_vals['max']:.2f}\n",
                    "- Min: {stats_vals['min']:.2f}\n",
                    "- Average: {stats_vals['mean']:.2f}\n",
                    "- Q1 (25th): {stats_vals['q1']:.2f}\n",
                    "- Median (50th): {stats_vals['median']:.2f}\n",
                    "- Q3 (75th): {stats_vals['q3']:.2f}\n",
                    "\n",
                    "Task: Predict the logarithmic views for the following videos. \n",
                    "You are provided with qualitative hints for each title indicating its score on the most significant semantic dimensions.\n",
                    "\n",
                    "Labels for dimension scores follow this distribution in the training data: \n",
                    "- significantly negative (5%)\n",
                    "- negative (10%)\n",
                    "- mildly negative (20%)\n",
                    "- neutral (30%)\n",
                    "- mildly positive (20%)\n",
                    "- positive (10%)\n",
                    "- significative positive (5%)\n",
                    "\n",
                    "IMPORTANT: A negative value (e.g., \"significantly negative\") in a given dimension may produce a positive impact on views depending on the channel's specific dynamics. This is why we provide both the dimension score and the analysis of how that dimension relates to views. Please use this information to minimize confusion and improve prediction accuracy.\n",
                    "\n",
                    "Return the results as a JSON object where keys are the video titles and values are the predicted logarithmic views (floats).\n",
                    "\n",
                    "Example:\n",
                    "{{\"Video Title 1\": 10.5, \"Video Title 2\": 11.2}}\n",
                    "\n",
                    "Videos to predict:\n",
                    "{video_list_str}\n",
                    "\"\"\"\n",
                    "        \n",
                    "        if i == 0:\n",
                    "            print(\"\\n--- First Batch Prompt ---\")\n",
                    "            print(prompt)\n",
                    "            print(\"--------------------------\\n\")\n",
                    "            \n",
                    "        res_text = get_gemini_completion(prompt, cache, f\"guided_inf_{cid}_batch_{i//10}\")\n",
                    "        batch_data = parse_json_response(res_text)\n",
                    "        \n",
                    "        valid_in_batch = 0\n",
                    "        if batch_data and isinstance(batch_data, dict):\n",
                    "            # Normalize keys to lower case for matching\n",
                    "            normalized_batch_data = {str(k).lower(): v for k, v in batch_data.items()}\n",
                    "            \n",
                    "            for idx_in_batch, v_orig in enumerate(batch):\n",
                    "                t_lower = v_orig['title'].lower()\n",
                    "                if t_lower in normalized_batch_data:\n",
                    "                    pred_val = normalized_batch_data[t_lower]\n",
                    "                    try:\n",
                    "                        res_obj = {\n",
                    "                            'title': v_orig['title'],\n",
                    "                            'predicted_log_views': float(pred_val),\n",
                    "                            'actual_log_views': np.log1p(v_orig['actual_views']),\n",
                    "                            'numeric_prediction': np.log1p(v_orig['predicted_views']),\n",
                    "                            'video_id': v_orig['video_id'],\n",
                    "                            'channel_id': cid,\n",
                    "                            'channel_name': cname\n",
                    "                        }\n",
                    "                        channel_results.append(res_obj)\n",
                    "                        valid_in_batch += 1\n",
                    "                    except (ValueError, TypeError):\n",
                    "                        pass\n",
                    "        \n",
                    "        print(f\"Batch {i//10 + 1}: {valid_in_batch}/{len(batch)} valid predictions.\")\n",
                    "            \n",
                    "    all_results.extend(channel_results)\n",
                    "\n",
                    "print(f\"\\nCompleted. Total valid predictions: {len(all_results)}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 5. Evaluation and Analysis\n",
                    "\n",
                    "We compare the accuracy of Gemini's guided predictions against the actual log-views and the OLS numeric baseline."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "df = pd.DataFrame(all_results)\n",
                    "\n",
                    "def calculate_metrics(group):\n",
                    "    actual = group['actual_log_views']\n",
                    "    llm_pred = group['predicted_log_views']\n",
                    "    num_pred = group['numeric_prediction']\n",
                    "    \n",
                    "    return pd.Series({\n",
                    "        'LLM MAE': mean_absolute_error(actual, llm_pred),\n",
                    "        'Numeric MAE': mean_absolute_error(actual, num_pred),\n",
                    "        'LLM R2': r2_score(actual, llm_pred),\n",
                    "        'Numeric R2': r2_score(actual, num_pred),\n",
                    "        'Count': len(group)\n",
                    "    })\n",
                    "\n",
                    "channel_summary = df.groupby('channel_name').apply(calculate_metrics).sort_values('LLM MAE')\n",
                    "display(channel_summary)\n",
                    "\n",
                    "global_llm_mae = mean_absolute_error(df['actual_log_views'], df['predicted_log_views'])\n",
                    "global_num_mae = mean_absolute_error(df['actual_log_views'], df['numeric_prediction'])\n",
                    "global_llm_r2 = r2_score(df['actual_log_views'], df['predicted_log_views'])\n",
                    "global_num_r2 = r2_score(df['actual_log_views'], df['numeric_prediction'])\n",
                    "\n",
                    "print(f\"\\n--- Global Metrics ---\")\n",
                    "print(f\"LLM Global MAE: {global_llm_mae:.3f} | Numeric Global MAE: {global_num_mae:.3f}\")\n",
                    "print(f\"LLM Global R2:  {global_llm_r2:.3f} | Numeric Global R2:  {global_num_r2:.3f}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Visualizing Prediction Accuracy"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "plt.figure(figsize=(12, 6))\n",
                    "channel_summary[['LLM MAE', 'Numeric MAE']].plot(kind='bar', figsize=(14, 7))\n",
                    "plt.title(\"MAE Comparison by Channel: Guided LLM vs. OLS Numeric\")\n",
                    "plt.ylabel(\"Mean Absolute Error (Log Views)\")\n",
                    "plt.xticks(rotation=45, ha='right')\n",
                    "plt.grid(axis='y', linestyle='--', alpha=0.7)\n",
                    "plt.show()\n",
                    "\n",
                    "plt.figure(figsize=(10, 10))\n",
                    "sns.scatterplot(data=df, x='actual_log_views', y='predicted_log_views', hue='channel_name', alpha=0.6)\n",
                    "plt.plot([df['actual_log_views'].min(), df['actual_log_views'].max()], \n",
                    "         [df['actual_log_views'].min(), df['actual_log_views'].max()], \n",
                    "         'r--', lw=2, label='Perfect Prediction')\n",
                    "plt.title(\"Actual vs. Guided LLM Predicted Log-Views\")\n",
                    "plt.xlabel(\"Actual Log-Views\")\n",
                    "plt.ylabel(\"Predicted Log-Views\")\n",
                    "plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 6. Export Results"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "df.to_json(OUTPUT_FILE, orient='records', indent=4)\n",
                    "print(f\"Results exported to {OUTPUT_FILE}\")"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.12"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }
    with open('numeric-inference/guided-inference.ipynb', 'w') as f:
        json.dump(nb, f, indent=2)

if __name__ == "__main__":
    create_notebook()
