import json
import os

def generate_notebook():
    nb = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Iterative Title Generation and Optimization\n",
                    "\n",
                    "This notebook uses the trained numeric inference models and qualitative LLM analysis to iteratively improve video titles for specific channels.\n",
                    "\n",
                    "**Export Path:** `/content/drive/MyDrive/numeric_inference_outputs/title_optimization_results.json`  \n",
                    "**Type:** JSON (List of objects containing original metadata, best title, and full iteration history)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Setup and Dependencies\n",
                    "# We only upgrade google-generativeai to avoid NumPy 2.0 conflicts in Colab\n",
                    "!pip install -q google-generativeai==0.8.3\n",
                    "!pip install -q sentence-transformers\n",
                    "\n",
                    "import os\n",
                    "import json\n",
                    "import time\n",
                    "import numpy as np\n",
                    "import pandas as pd\n",
                    "import hashlib\n",
                    "from google.colab import drive, userdata\n",
                    "import google.generativeai as genai\n",
                    "from sklearn.decomposition import PCA\n",
                    "from sentence_transformers import SentenceTransformer\n",
                    "\n",
                    "drive.mount('/content/drive')\n",
                    "\n",
                    "GEMINI_API_KEY = userdata.get('GOOGLE_API_KEY')\n",
                    "genai.configure(api_key=GEMINI_API_KEY)\n",
                    "MODEL_NAME = 'gemini-3.1-flash-lite-latest'\n",
                    "EMBEDDING_MODEL_NAME = 'all-MiniLM-L6-v2'\n",
                    "\n",
                    "BASE_PATH = '/content/drive/MyDrive/numeric_inference_outputs/'\n",
                    "EVAL_DATA_PATH = os.path.join(BASE_PATH, 'top_significant_channels_eval.json')\n",
                    "LLM_RESULTS_PATH = os.path.join(BASE_PATH, 'llm_analysis_results.json')\n",
                    "EMBEDDING_CACHE_PATH = os.path.join(BASE_PATH, 'video_title_embeddings_latest.json')\n",
                    "TRAIN_DATA_PATH = os.path.join(BASE_PATH, 'train_structured_latest.json')\n",
                    "GENERATION_CACHE_PATH = os.path.join(BASE_PATH, 'title_generation_cache.json')\n",
                    "FINAL_RESULTS_PATH = os.path.join(BASE_PATH, 'title_optimization_results.json')\n",
                    "\n",
                    "embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Data Loading\n",
                    "with open(EVAL_DATA_PATH, 'r') as f:\n",
                    "    eval_dataset = json.load(f)\n",
                    "\n",
                    "with open(LLM_RESULTS_PATH, 'r') as f:\n",
                    "    llm_analysis = json.load(f)\n",
                    "\n",
                    "with open(EMBEDDING_CACHE_PATH, 'r') as f:\n",
                    "    embedding_cache = json.load(f)\n",
                    "\n",
                    "with open(TRAIN_DATA_PATH, 'r') as f:\n",
                    "    train_data = json.load(f)\n",
                    "\n",
                    "def load_gen_cache():\n",
                    "    if os.path.exists(GENERATION_CACHE_PATH):\n",
                    "        with open(GENERATION_CACHE_PATH, 'r') as f:\n",
                    "            return json.load(f)\n",
                    "    return {}\n",
                    "\n",
                    "def save_gen_cache(cache):\n",
                    "    with open(GENERATION_CACHE_PATH, 'w') as f:\n",
                    "        json.dump(cache, f, indent=4)\n",
                    "\n",
                    "generation_cache = load_gen_cache()\n",
                    "print(\"Data and generation cache loaded successfully.\")"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Reconstruct global PCA from training data\n",
                    "all_train_embeddings = []\n",
                    "for channel in train_data:\n",
                    "    for video in channel['videos']:\n",
                    "        all_train_embeddings.append(embedding_cache[video['title']])\n",
                    "\n",
                    "X_train = np.array(all_train_embeddings)\n",
                    "pca = PCA(n_components=15, random_state=42)\n",
                    "pca.fit(X_train)\n",
                    "\n",
                    "print(f\"Reconstructed PCA with {pca.n_components_} components.\")"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Utility functions for prediction\n",
                    "def predict_views(titles, channel_id, channel_models_params):\n",
                    "    \"\"\"\n",
                    "    Predict log-views for a list of titles.\n",
                    "    \"\"\"\n",
                    "    # 1. Embed titles\n",
                    "    embs = embedding_model.encode(titles)\n",
                    "    \n",
                    "    # 2. Project to PCA\n",
                    "    reduced = pca.transform(embs)\n",
                    "    \n",
                    "    # 3. Predict using parameters\n",
                    "    # Data schema from inference notebook:\n",
                    "    # intercept: float(model.params[0])\n",
                    "    # coefficients: model.params[1:].tolist()\n",
                    "    params = channel_models_params[channel_id]\n",
                    "    intercept = params['intercept']\n",
                    "    coeffs = np.array(params['coefficients'])\n",
                    "    \n",
                    "    predictions = (reduced @ coeffs) + intercept\n",
                    "    \n",
                    "    return predictions.tolist()"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Configuration for target channels\n",
                    "TARGET_CHANNELS_REQUESTED = [\"20VC with Harry Stebbings\", \"A16z\"]\n",
                    "target_channel_data = []\n",
                    "channel_models_params = {}\n",
                    "\n",
                    "# Case-insensitive matching\n",
                    "target_channels_lower = [c.lower() for c in TARGET_CHANNELS_REQUESTED]\n",
                    "\n",
                    "for channel in eval_dataset:\n",
                    "    if channel['channel_name'].lower() in target_channels_lower:\n",
                    "        target_channel_data.append(channel)\n",
                    "        channel_models_params[channel['channel_id']] = {\n",
                    "            'coefficients': channel['model']['coefficients'],\n",
                    "            'intercept': channel['model']['intercept']\n",
                    "        }\n",
                    "\n",
                    "print(f\"Targeted {len(target_channel_data)} channels.\")"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def get_gemini_response(prompt):\n",
                    "    prompt_hash = hashlib.md5(prompt.encode()).hexdigest()\n",
                    "    if prompt_hash in generation_cache:\n",
                    "        return generation_cache[prompt_hash]\n",
                    "\n",
                    "    model = genai.GenerativeModel(MODEL_NAME)\n",
                    "    for _ in range(3):\n",
                    "        try:\n",
                    "            response = model.generate_content(prompt)\n",
                    "            text = response.text\n",
                    "            generation_cache[prompt_hash] = text\n",
                    "            save_gen_cache(generation_cache)\n",
                    "            return text\n",
                    "        except Exception as e:\n",
                    "            print(f\"Error: {e}. Retrying...\")\n",
                    "            time.sleep(5)\n",
                    "    return \"\"\n",
                    "\n",
                    "def parse_titles(text):\n",
                    "    \"\"\"Extract 10 titles from LLM response.\"\"\"\n",
                    "    lines = text.strip().split('\\n')\n",
                    "    titles = []\n",
                    "    for line in lines:\n",
                    "        line = line.strip()\n",
                    "        if not line: continue\n",
                    "        # Strip leading numbers or bullets\n",
                    "        if line[0].isdigit() or line[0] in ['-', '*']:\n",
                    "            parts = line.split('. ', 1) if '.' in line else line.split(' ', 1)\n",
                    "            if len(parts) > 1:\n",
                    "                titles.append(parts[1].strip().strip('\"'))\n",
                    "            else:\n",
                    "                titles.append(line.strip('-* ').strip('\"'))\n",
                    "        else:\n",
                    "            titles.append(line.strip('\"'))\n",
                    "        if len(titles) == 10: break\n",
                    "    return titles[:10]"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Iterative Optimization Loop\n",
                    "results = []\n",
                    "\n",
                    "for channel in target_channel_data:\n",
                    "    cid = channel['channel_id']\n",
                    "    cname = channel['channel_name']\n",
                    "    \n",
                    "    global_desc = llm_analysis['global_performance_descriptions'].get(cid, \"\")\n",
                    "    dim_analysis = llm_analysis['channel_significant_dimension_analysis'].get(cid, \"\")\n",
                    "    \n",
                    "    # Select 10 test videos\n",
                    "    test_vids = channel['test_videos'][:10]\n",
                    "    \n",
                    "    for vid in test_vids:\n",
                    "        base_title = vid['title']\n",
                    "        base_pred = float(np.log1p(vid['actual_views']))\n",
                    "        \n",
                    "        print(f\"\\nOptimizing title for {cname}: '{base_title}'\")\n",
                    "        \n",
                    "        history = [] # To store list of {iteration, titles: [{text, score}]}\n",
                    "        \n",
                    "        for i in range(5):\n",
                    "            print(f\"  Iteration {i+1}...\")\n",
                    "            \n",
                    "            # Build Prompt\n",
                    "            best_so_far = max([base_pred] + [max([t['score'] for t in h['titles']]) for h in history]) if history else base_pred\n",
                    "            prompt = f\"\"\"You are an expert YouTube title strategist for the channel '{cname}'.\n",
                    "Channel success drivers:\n",
                    "{global_desc}\n",
                    "\n",
                    "Semantic performance analysis:\n",
                    "{dim_analysis}\n",
                    "\n",
                    "Original Title: {base_title}\n",
                    "Current best predicted performance (log-views): {best_so_far:.4f}\n",
                    "\"\"\"\n",
                    "            if history:\n",
                    "                # Include top 3 and bottom 3 from previous iterations for feedback\n",
                    "                all_prev = []\n",
                    "                for h in history:\n",
                    "                    for t_obj in h['titles']:\n",
                    "                        all_prev.append(t_obj)\n",
                    "                all_prev.sort(key=lambda x: x['score'], reverse=True)\n",
                    "                \n",
                    "                prompt += \"\\nPrevious suggestions feedback:\\n\"\n",
                    "                prompt += \"Top performing suggestions:\\n\"\n",
                    "                for t_obj in all_prev[:3]:\n",
                    "                    prompt += f\"- {t_obj['text']} (Score: {t_obj['score']:.4f})\\n\"\n",
                    "                \n",
                    "                prompt += \"Lower performing suggestions (Avoid these patterns):\\n\"\n",
                    "                for t_obj in all_prev[-3:]:\n",
                    "                    prompt += f\"- {t_obj['text']} (Score: {t_obj['score']:.4f})\\n\"\n",
                    "            \n",
                    "            prompt += \"\\nTask: Generate 10 new, improved titles for this video that will maximize views based on the channel's success drivers and semantic analysis. Return ONLY the 10 titles, one per line.\"\n",
                    "            \n",
                    "            llm_text = get_gemini_response(prompt)\n",
                    "            new_titles = parse_titles(llm_text)\n",
                    "            \n",
                    "            if not new_titles:\n",
                    "                 print(\"    Error: No titles generated.\")\n",
                    "                 continue\n",
                    "\n",
                    "            preds = predict_views(new_titles, cid, channel_models_params)\n",
                    "            \n",
                    "            iter_titles = []\n",
                    "            for t, p in zip(new_titles, preds):\n",
                    "                iter_titles.append({'text': t, 'score': p})\n",
                    "            \n",
                    "            history.append({\n",
                    "                'iteration': i + 1,\n",
                    "                'titles': iter_titles\n",
                    "            })\n",
                    "            \n",
                    "            # Identify best this round\n",
                    "            best_idx = np.argmax(preds)\n",
                    "            diff = preds[best_idx] - base_pred\n",
                    "            sign = \"+\" if diff >= 0 else \"\"\n",
                    "            print(f\"    Best this round: '{new_titles[best_idx]}' ({sign}{diff:.4f} log-views)\")\n",
                    "\n",
                    "        # Collect final results for this video\n",
                    "        all_optimized = []\n",
                    "        for h in history:\n",
                    "            all_optimized.extend(h['titles'])\n",
                    "        \n",
                    "        all_optimized.sort(key=lambda x: x['score'], reverse=True)\n",
                    "        best_title_obj = all_optimized[0]\n",
                    "        \n",
                    "        results.append({\n",
                    "            'channel': cname,\n",
                    "            'video_id': vid['video_id'],\n",
                    "            'original_title': base_title,\n",
                    "            'original_score': base_pred,\n",
                    "            'best_optimized_title': best_title_obj['text'],\n",
                    "            'best_optimized_score': best_title_obj['score'],\n",
                    "            'improvement': best_title_obj['score'] - base_pred,\n",
                    "            'improvement_pct': (np.expm1(best_title_obj['score']) - np.expm1(base_pred)) / np.expm1(base_pred) * 100 if np.expm1(base_pred) > 0 else 0,\n",
                    "            'history': history\n",
                    "        })\n",
                    "\n",
                    "print(\"\\nOptimization complete.\")"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Export final results\n",
                    "with open(FINAL_RESULTS_PATH, 'w') as f:\n",
                    "    json.dump(results, f, indent=4)\n",
                    "print(f\"Final results exported to {FINAL_RESULTS_PATH}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Final Report"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "df_results = pd.DataFrame(results)\n",
                    "\n",
                    "# Use the matched channel names for reporting\n",
                    "target_channel_names = [c['channel_name'] for c in target_channel_data]\n",
                    "for channel in target_channel_names:\n",
                    "    print(f\"\\n=== {channel} Summary ===\")\n",
                    "    chan_df = df_results[df_results['channel'] == channel]\n",
                    "    for _, row in chan_df.iterrows():\n",
                    "        print(f\"Original: {row['original_title']}\")\n",
                    "        print(f\"Best:     {row['best_optimized_title']}\")\n",
                    "        print(f\"Expected Improvement: {row['improvement']:.4f} log-views ({row['improvement_pct']:.2f}%)\")\n",
                    "        print(\"-\" * 20)\n",
                    "\n",
                    "print(f\"\\nAverage Improvement across all videos: {df_results['improvement'].mean():.4f} log-views\")"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.12"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

    with open("title generation/title_generator.ipynb", "w") as f:
        json.dump(nb, f, indent=2)

if __name__ == "__main__":
    generate_notebook()
    print("Notebook generated: title generation/title_generator.ipynb")
